"""Init message and interaction

Revision ID: b77bb559f678
Revises: 
Create Date: 2023-11-08 04:17:55.802076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b77bb559f678"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interaction",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_interaction_created_at"), "interaction", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_interaction_updated_at"), "interaction", ["updated_at"], unique=False
    )
    op.create_table(
        "message",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("interaction_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_created_at"), "message", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_message_role"), "message", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_role"), table_name="message")
    op.drop_index(op.f("ix_message_created_at"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_interaction_updated_at"), table_name="interaction")
    op.drop_index(op.f("ix_interaction_created_at"), table_name="interaction")
    op.drop_table("interaction")
    # ### end Alembic commands ###
